controller_joint_names: ['', 'left_forward_wheel_2_base_joint', 'left_back_wheel_base_joint', 'right_back_wheel_2_base_joint', 'right_forward_wheel_2_base_joint', 'hua_tai_2_zhou_cheng_joint', 'fixed_hua_kuai_2_hua_tai_joint', ]
